version: 0.2

phases:
  build:
    commands:
      # experiments with environment variables values
      - echo CODEBUILD_BUILD_ID $CODEBUILD_BUILD_ID
      - echo CODEBUILD_BUILD_NUMBER $CODEBUILD_BUILD_NUMBER
      - echo CODEBUILD_RESOLVED_SOURCE_VERSION $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo CODEBUILD_SOURCE_REPO_URL $CODEBUILD_SOURCE_REPO_URL
      - echo CODEBUILD_SOURCE_VERSION $CODEBUILD_SOURCE_VERSION
      - echo CODEBUILD_SRC_DIR $CODEBUILD_SRC_DIR
      - echo CODEBUILD_WEBHOOK_BASE_REF $CODEBUILD_WEBHOOK_BASE_REF
      - echo CODEBUILD_WEBHOOK_PREV_COMMIT $CODEBUILD_WEBHOOK_PREV_COMMIT
      - echo CODEBUILD_WEBHOOK_HEAD_REF $CODEBUILD_WEBHOOK_HEAD_REF
      - echo CODEBUILD_WEBHOOK_TRIGGER $CODEBUILD_WEBHOOK_TRIGGER
      - echo HOME $HOME
      - echo Done